package core

const step1A = "(1.A) The large prime is equal to the large modulus p"
const step1B = "(1.B) The small prime is equal to the prime q"
const step1C = "(1.C) The cofactor is equal to r = (p − 1)/q"
const step1D = "(1.D) The generator is equal to the generator g"

const step2A = "(2.A) The challenge is correctly computed"
const step2B = "(2.B) The equation is satisfied"

const step3A = "(3.A) The joint public election key is computed correctly"
const step3B = "(3.B) The extended base hash is computed correctly"

const step4A1 = "(4.A) a is in the set Z_p^r"
const step4A2 = "(4.A) b is in the set Z_p^r"
const step4A3 = "(4.A) a0 is in the set Z_p^r"
const step4A4 = "(4.A) b0 is in the set Z_p^r"
const step4A5 = "(4.A) a1 is in the set Z_p^r"
const step4A6 = "(4.A) b1 is in the set Z_p^r"
const step4B = "(4.B) The challenge value c is computed correctly"
const step4C1 = "(4.C) c0 is in Zq"
const step4C2 = "(4.C) c1 is in Zq"
const step4C3 = "(4.C) v0 is in Zq"
const step4C4 = "(4.C) v1 is in Zq"
const step4D = "(4.D) The equation c=(c0+c1) mod q is satisfied"
const step4E = "(4.E) The equation g^v0=a0*a^c0 is satisfied"
const step4F = "(4.F) The equation g^v1=a1*a^c1 is satisfied"
const step4G = "(4.G) The equation K^v0=b0*b^c0 is satisfied"
const step4H = "(4.H) The equation g^c1=b0*b^c0 is satisfied"

const step5A = "(5.A) The number of placeholder positions matches the selection limit"
const step5B1 = "(5.B) The a hat is computed correctly"
const step5B2 = "(5.B) The b hat is computed correctly"
const step5C = "(5.C) The given value V is in Zq"
const step5D1 = "(5.D) The given value a are in Zp^r"
const step5D2 = "(5.D) The given values b are in Zp^r"
const step5E = "(5.E) The challenge value is correctly computed"
const step5F = "(5.F) The equation is satisfied"
const step5G = "(5.G) The equation is satisfied"

const step6A = "(6.A) The confirmation code for ballot is computed correct"
const step6B = "(6.B) No duplicate confirmation codes found"

const step7A = "(7.A) A is calculated correctly"
const step7B = "(7.B) B is calculated correctly"

const step8A = "(8.A) The value v is in the set Zq for"
const step8B1 = "(8.B) The value a is in the set Zqr for"
const step8B2 = "(8.B) The value b is in the set Zqr for"
const step8C = "(8.C) The challenge is computed correctly"
const step8D = "(8.D) The equation is satisfied"
const step8E = "(8.E) The equation is satisfied"

const step9A = "(9.A) The given value v is in Zq"
const step9B1 = "(9.B) The given value a is in Zp^r"
const step9B2 = "(9.B) The given value b is in Zp^r"
const step9C = "(9.C) The challenge value c is correct"
const step9D = "(9.D) The equation is satisfied"
const step9E = "(9.E) The equation is satisfied"

const step10A = "(10.A) Coefficient check for guardian"
const step10B = "(10.B) Correct tally share"

const step11A = "(11.A) The equation is satisfied"
const step11B = "(11.B) The equation is satisfied"
const step11C = "(11.C) Tally label exists in election manifest"
const step11D = "(11.D) The option in the contest occurs as an option for the contest in the election manifest"
const step11E = "(11.E) The option text label for the contest in the election manifest occurs as a option in the plaintext tally"
const step11F = "(11.F) For each contest text label that occurs in at least one submitted ballot, that contest text label occurs in the list of contests in the plaintext tally"

const step12A = "(12.A) The given value v is in the set Zq"
const step12B1 = "(12.B) The given value a is in the set Zpr"
const step12B2 = "(12.B) The given value b is in the set Zpr"
const step12C = "(12.C) The challenge is computed correctly"
const step12D = "(12.D) The equation is satisfied"
const step12E = "(12.E) The equation is satisfied"

const step13A = "(13.A) The given value v is in Zq"
const step13B1 = "(13.B) The given value a is in the set Zpr"
const step13B2 = "(13.B) The given value b is in the set Zpr"
const step13C = "(13.C) The challenge is computed correctly"
const step13D = "(13.D) The equation is satisfied"
const step13E = "(13.E) The equation is satisfied"

const step14A = "(14.A) ??"
const step14B = "(14.B) Correct missing decryption share"

const step15A = "(15.A) The equation is satisfied"
const step15B = "(15.B) The equation is satisfied"

const step16A = "(16.A) For each option in the contest, the selection V is either a 0 or a 1"
const step16B = "(16.B) The sum of all selections in the contest is at most the selection limit L for that contest"
const step16C = "(16.C) The contest text label occurs as a contest label in the list of contests in the election manifest"
const step16D = "(16.D) For each non-placeholder selection the option text label occurs as an option label for the contest in the election manifest"
const step16E = "(16.E) For each option text label listed for this contest in the election manifest, the option label occurs for a non-placeholder option"

const step17A = "(17.A) The given value v is in the set Zq"
const step17B1 = "(17.B) The given value a is in the set Zqr"
const step17B2 = "(17.B) The given value b is in the set Zqr"
const step17C = "(17.C) The challenge is correctly computed"
const step17D = "(17.D) The equation is satisfied"
const step17E = "(17.E) The equation is satisfied"

const step18A = "(18.A) The value v is in the set Zq"
const step18B1 = "(18.B) The value a is in the set Zqr"
const step18B2 = "(18.B) The value b is in the set Zqr"
const step18C = "(18.C) The challenge is computed correctly"
const step18D = "(18.D) The equation is satisfied"
const step18E = "(18.E) The equation is satisfied"

const step19A = "(19.A) The equation is satisfied"
